#!/bin/bash
#SBATCH --job-name=main
#SBATCH --output=output.out
#SBATCH --error=error.error
#SBATCH --time=24:00:00
#SBATCH --partition short
#SBATCH --ntasks 28
#SBATCH --nodes 1
#SBATCH --mem=250Gb

module load python/3.7.0

python -u main.py